# Generated by Django 5.2.2 on 2025-06-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_chatsession_chatmessage_usersession'),
    ]

    operations = [
    ]
